# -*- coding: utf-8 -*-
"""score.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PAFny8scbWgfcWO9Oq-fBoW6aNntgSoj
"""

import pickle

with open(r"C:\Users\Samriddha\OneDrive\Desktop\msc@cmi\cmi sem 4\Applied ML\best_model.pkl", 'rb') as file:
    best_model = pickle.load(file)

import sklearn
import numpy as np
import pandas as pd

from typing import Tuple
import numpy as np

def score(text: str, model, threshold: float) -> Tuple[bool, float]:

    # Predict using the loaded model
    predicted_prob = best_model.predict_proba([text])[0, 1]

    # Convert probability to boolean prediction based on the threshold
    prediction = predicted_prob > threshold

    return prediction, predicted_prob

# test=pd.read_csv(r"C:\Users\Samriddha\OneDrive\Desktop\msc@cmi\cmi sem 4\Applied ML\test.csv")

# test

# import random

# # Generate a random integer between a specified range (inclusive)
# r = random.randint(0, 573)#number of rows in train.csv is 573

# text= test.iat[2,0]

# score(text,best_model,0.5)